#! /usr/bin/env python
# -*- coding: utf-8 -*-

import pandas as pd
import openpyxl
import json
import requests

from openpyxl.styles import Border, Font, Side, PatternFill, Alignment
from openpyxl.utils.dataframe import dataframe_to_rows

"""
term=query(bools)
    no need ""
    term=asthma[mh]+OR+hay+fever[mh]; [mh] means mesh terms
retmax=# of articles
"""
KEYWORS = XXXX
rm = 
query = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=KEYWORD&retmax=rm&retmode=json'

### response is dictionary type, and curate pmid
response = requests.get(query)
response_json = response.json()
pmids = response_json['esearchresult']['idlist']

### pmid query making 
URL = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&retmode=json&id='
queries = [URL + pmid for pmid in pmids]

### dictionary make for json data
responses = {}
for query in queries:
    response = requests.get(query)
    res_json = response.json()["result"]
    responses.update(res_json)

"""    
list make for accumulating data
keys check via print(responses['30478810'].keys())
"""
Summaries = [{'pmid':pmid, 
            'Title':responses[pmid]['title'], 
            'Author':responses[pmid]['sortfirstauthor'], 
            'Journal' : responses[pmid]['source'],
            'Pubdate':responses[pmid]['epubdate']} for pmid in pmids]

### make datafram
data  = pd.DataFrame(columns = ['PMID','Title', 'Author', 'Journal', 'Pubdate'])

"""
make list from each column of summaries
input each dataframe from the lists
"""
PMIDs = [ i['pmid'] for i in Summaries ]
Titles = [ i['Title'] for i in Summaries ]
Authors = [ i['Author'] for i in Summaries ]
Journals = [ i['Journal'] for i in  Summaries ]
Pubdates = [ i['Pubdate'] for i in Summaries ]

data['PMID'] = PMIDs
data['Title'] = Titles
data['Author'] = Authors
data['Journal'] = Journals
data['Pubdate'] = Pubdates

"""
make workbook
choose active sheet on the workbook
change name of the sheet
"""
wb = openpyxl.Workbook()
ws = wb.active
ws.title='Articles'

### Style of sheet
# Font
normal_font = Font(name = "Century Gothic",sz = 9,b = False)
header_font = Font(name = "Century Gothic", sz = 9, b = True, color = 'FFFFFFFF')
# Header
header_fill = PatternFill(patternType = "solid", fgColor = "FF808080")
header_center = Alignment(horizontal='center',vertical = 'center')
header_border = Border(
        outline=True,
        left=Side(style='thin', color='FF000000'),
        right=Side(style='thin', color='FF000000'),
        top=Side(style='thin', color='FF000000'),
        bottom=Side(style='thin', color='FF000000')
        )

### pandas dataframe change to openpyxl
for r in dataframe_to_rows(data, index=False, header=True):
    ws.append(r)
    
for row in ws:
    for cell in row:
        cell.font = normal_font
        
### Header style      
header_cell = ['A1', 'B1', 'C1', 'D1', 'E1']
for cell in header_cell:
    ws[cell].font = header_font
    ws[cell].fill = header_fill
    ws[cell].alignment = header_center
    ws[cell].border = header_border
    
### Export
wb.save("XXXX.xlsx")
