#! /usr/bin/env python
# -*- coding: utf-8 -*-

import pandas as pd
import openpyxl
import json
import requests

from openpyxl.styles import Border, Font, Side, PatternFill, Alignment
from openpyxl.utils.dataframe import dataframe_to_rows

"""
queryを作成する
term=検索文字列。ブール演算子も可
例：term=asthma[mh]+OR+hay+fever[mh]。[mh]はMeSH Termsの記号
retmax=検索数
"""
query = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=KEYWORD&retmax=1000&retmode=json'

### responseは辞書型データで、ここからpmidだけ抜き出す
response = requests.get(query)
response_json = response.json()
pmids = response_json['esearchresult']['idlist']

### pmid毎のクエリを作成
URL = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&retmode=json&id='
queries = [URL + pmid for pmid in pmids]

### jsonデータを格納する辞書を作成
responses = {}
for query in queries:
    response = requests.get(query)
    res_json = response.json()["result"]
    responses.update(res_json)

"""    
データとして取得するものをリスト型に入れる
print(responses['30478810'].keys())などで必要なkeysを確認可
"""
Summaries = [{'pmid':pmid, 
            'Title':responses[pmid]['title'], 
            'Author':responses[pmid]['sortfirstauthor'], 
            'Journal' : responses[pmid]['source'],
            'Pubdate':responses[pmid]['epubdate']} for pmid in pmids]

### 空のデータフレームを作成
data  = pd.DataFrame(columns = ['PMID','Title', 'Author', 'Journal', 'Pubdate'])

### Summariesよりカラム毎のリストを作成する
PMIDs = [ i['pmid'] for i in Summaries ]
Titles = [ i['Title'] for i in Summaries ]
Authors = [ i['Author'] for i in Summaries ]
Journals = [ i['Journal'] for i in  Summaries ]
Pubdates = [ i['Pubdate'] for i in Summaries ]

### 作成したリストそれぞれをデータフレームへ格納する
data['PMID'] = PMIDs
data['Title'] = Titles
data['Author'] = Authors
data['Journal'] = Journals
data['Pubdate'] = Pubdates

"""
ワークブックの作成
ワークブックのアクティブになっているシートの選択
シートの名前を変更
"""
wb = openpyxl.Workbook()
ws = wb.active
ws.title='Articles'

### Excelとして書き出す際のスタイル設定
#フォントの設定
normal_font = Font(name = "Century Gothic",sz = 9,b = False)
header_font = Font(name = "Century Gothic", sz = 9, b = True, color = 'FFFFFFFF')
#ヘッダーの塗りの設定
header_fill = PatternFill(patternType = "solid", fgColor = "FF808080")
#ヘッダーを中央揃えにする設定
header_center = Alignment(horizontal='center',vertical = 'center')    
#ヘッダーを太字にする設定
header_border = Border(
        outline=True,
        left=Side(style='thin', color='FF000000'),
        right=Side(style='thin', color='FF000000'),
        top=Side(style='thin', color='FF000000'),
        bottom=Side(style='thin', color='FF000000')
        )

### pandasデータフレームをopenpyxl
for r in dataframe_to_rows(data, index=False, header=True):
    ws.append(r)
    
### 設定したスタイルを適用    
for row in ws:
    for cell in row:
        cell.font = normal_font
        
### headerのスタイルを指定      
header_cell = ['A1', 'B1', 'C1', 'D1', 'E1']
for cell in header_cell:
    ws[cell].font = header_font
    ws[cell].fill = header_fill
    ws[cell].alignment = header_center
    ws[cell].border = header_border
    
### エクセルファイルの保存
wb.save("XXXX.xlsx")
