#! /usr/bin/env python
# -*- coding: utf-8 -*-

"""
Predict melting temperature
"""

seq = 'ATGAGCCCTGAAGTG'      
pair = [seq[i:i+2] for i in range(len(seq)-1)]
print(pair)

param = {
    'AA':[-9.1, -24],
    'TT':[-9.1, -24],
    'AT':[-8.6, -23.9],
    'TA':[-6, -16.9],
    'CA':[-5.8, -12.9],
    'TG':[-5.8, -12.9],
    'GT':[-6.5, -17.3],
    'AC':[-6.5, -17.3],
    'CT':[-7.8, -20.8],
    'AG':[-7.8, -20.8],
    'GA':[-5.6, -13.5],
    'TC':[-5.6, -13.5],
    'CG':[-11.9, -27.8],
    'GC':[-11.1, -26.7],
    'GG':[-11, -26.6],
    'CC':[-11, -26.6]
        }
        
H_list = [param[i][0] for i in pair]
S_list = [param[i][1] for i in pair]
sumH = sum(H_list)
sumS = sum(S_list) 

import math
mol = 0.5*(10**(-6))
Na = 50*(10**(-3))

tm = (1000*sumH/(-10.8+sumS+1.978*math.log(mol/4)))-273.15+16.6*math.log10(Na)
print(tm)
