#!/usr/bin/env python3
import pandas as pd
import numpy as np
import math
from scipy import stats

def log2FC(x):
    x1 = x.iloc[0:3]
    x2 = x.iloc[3:6]
    Ave1 = np.average(x1)
    Ave2 = np.average(x2)
    
    ### Check the averages
    if Ave1 == 0 and Ave2 == 0:
        return 0
    elif Ave1 > 0 and Ave2 > 0:
        fc = math.log2(Ave1/Ave2)
        return fc
    elif Ave1 >0 and Ave2 == 0:
        return 10000
    elif Ave1 == 0 and Ave2 > 0:
        return -10000
    else:
        return "error"

def pvalue(x):
    x1 = x.iloc[0:3]
    x2 = x.iloc[3:6]
    
    ### Welch test
    x1_var = np.var(x1, ddof=1)
    x2_var = np.var(x2, ddof=1)
    x1_df = len(x1) - 1
    x2_df = len(x2) - 1
    Fvalue = x1_var / x2_var
    p_value = stats.f.cdf(Fvalue, x1_df, x2_df)
    
    ### Student test
    if p_value >= 0.05:
        t, p = stats.ttest_ind(x1, x2, equal_var = True)
        return p
    else:
        t, p = stats.ttest_ind(x1, x2, equal_var = False)
        return p

"""
### Test
df = pd.DataFrame({
    'price1': [1000, 2000, 3000, 4000, 5000, 6000, 7000],
    'price2': [50, 60, 70, 80, 90, 100, 110],
    'price3': [100, 200, 250, 300, 150, 200, 400],
    'price4': [1, 2, 3, 4, 5, 6, 7]
})

print(df)
df.apply(log2FC)

### Output1
   price1  price2  price3  price4
0    1000      50     100       1
1    2000      60     200       2
2    3000      70     250       3
3    4000      80     300       4
4    5000      90     150       5
5    6000     100     200       6
6    7000     110     400       7

#### Output2
price1   -1.321928
price2   -0.584963
price3   -0.241008
price4   -1.321928
dtype: float64
